### ISSUE TITLE
group management via seat

### ISSUE THREAD

**Issue by draymah** [herpaderpaldent/seat-discourse#14]
How link / manage groups in discourse via SeAT ?

**Comment by herpaderpaldent** [comment]
Via roles management. 

![image](https://user-images.githubusercontent.com/6583519/49633523-e8a37700-f9f9-11e8-983d-712fcb4871a3.png)

**Comment by draymah** [comment]
Do you create the groups in Discourse first ? Im a superuser in seat, no Admin panel appearing in Discourse

**Comment by herpaderpaldent** [comment]
in order to create an API-Key or enable SSO you need to be admin of discourse. Here is the documentation to do this: https://herpaderpaldent.github.io/seat-discourse/installation/package_installation/#create-api-key 

Afterwards discourse groups are managed/created from seat.

**Comment by draymah** [comment]
API linked and working, SSO working as well, superuser role assigned to account linked to the same SSO account, is there a cron i need to run ? 

What a the permissions in SeAT on the View Groups Role

**Comment by herpaderpaldent** [comment]
Please join Slack as we are flooding the plugin channel with this support case: https://eveseat-slack.herokuapp.com/
