### ISSUE TITLE
Call to undefined method GuzzleHttp\Exception\ClientException::map()

### ISSUE THREAD

**Issue by neosysdate** [herpaderpaldent/seat-discourse#25]
When i clicked my seat discourse menu my site shows this error

(1/1) FatalThrowableError
Call to undefined method GuzzleHttp\Exception\ClientException::map()

![errorimage](https://user-images.githubusercontent.com/63350831/78782928-c77fdb80-79dd-11ea-931b-2ae8dd349453.png)

**Comment by xenon007** [comment]
I have the same problem too

**Comment by flyingferret** [comment]
also have the same error after updating my forums :(

**Comment by goemktg** [comment]
I guess it's a problem below:
https://github.com/herpaderpaldent/seat-discourse/issues/24
Developers are working on it, so we can wait a little while or go back to the previous version of the forum.

**Comment by herpaderpaldent** [comment]
https://github.com/herpaderpaldent/seat-discourse/pull/30#issuecomment-615439083 the two submitting a fix did not check back with me so i am absolutely clueless about wether the current dev branch works or not. 
Follow the instructions and let me know if it is working?

**Comment by flyingferret** [comment]
on dev branch getting the following error 

``` local.ERROR: Call to undefined method GuzzleHttp\Exception\ClientException::getStatusCode() {"userId":91089388,"email":"**********@googlemail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method GuzzleHttp\\Exception\\ClientException::getStatusCode() at /var/www/seat/vendor/herpaderpaldent/seat-discourse/src/Action/Discourse/Groups/Get.php:44)```

Full stacktrace  https://pastebin.com/inA8GSVN

```
| Vendor          | Package Name           | Installed Version |
| --------------- | ---------------------- | ----------------- |
| eveseat         | api                    | 3.0.8             |
| eveseat         | console                | 3.0.5             |
| eveseat         | eveapi                 | 3.0.19            |
| eveseat         | notifications          | 3.0.6             |
| eveseat         | services               | 3.0.11            |
| eveseat         | web                    | 3.0.28            |
| flyingferret    | seat-whtools           | 0.1.6             |
| herpaderpaldent | seat-groups            | 1.7.2             |
| kassie          | calendar               | 3.0.16            |
| warlof          | seat-connector         | 1.4.3             |
| warlof          | seat-discord-connector | 4.0.4             |
| warlof          | seat-teamspeak         | 4.1.2             |
```
```

**Comment by herpaderpaldent** [comment]
Yep ... seems one of the contributions was not complete. I got an idea whats up. I'll update and you could retest it

**Comment by flyingferret** [comment]
rodger, let me know when

**Comment by herpaderpaldent** [comment]
@flyingferret wanna try again?

**Comment by flyingferret** [comment]
will do

**Comment by flyingferret** [comment]
get the following error.  

[2020-04-24 20:17:44] local.ERROR: Client error: `POST http://forum.whsoc.org//admin/groups` resulted in a `422 Unprocessable Entity` response:
{"errors":["Name must be no more than 20 characters"]}
 {"userId":91089388,"email":"*********@googlemail.com","exception":"[object] (Herpaderpaldent\\Seat\\SeatDiscourse\\Exceptions\\DiscourseGuzzleException(code: 422): Client error: `POST http://forum.whsoc.org//admin/groups` resulted in a `422 Unprocessable Entity` response:
{\"errors\":[\"Name must be no more than 20 characters\"]}
 at /var/www/seat/vendor/herpaderpaldent/seat-discourse/src/Action/Discourse/Groups/Create.php:46)

Stack trace :  https://pastebin.com/G7GdxcLY

**Comment by herpaderpaldent** [comment]
Well this now sounds like it's working just your role name is too long:

`["Name must be no more than 20 characters"]`

**Comment by flyingferret** [comment]
thank god i got better at sql now, changed the role names and it works, might be worth adding a note to the readme no sill role names lol

**Comment by herpaderpaldent** [comment]
I guess this is solved. Feel free to reopen if not
