### ISSUE TITLE
forum link

### ISSUE THREAD

**Issue by trekkie357** [herpaderpaldent/seat-discourse#31]
ok i followed the guide and the discourse option shows up but when i click on forum it goes to wrong url.
 did i make a wrong setting or something?

**Comment by herpaderpaldent** [comment]
What's in the log? What does the error exactly say?

**Comment by trekkie357** [comment]
not really an error its going to example.com/discourse   instead of discourse.example.com

**Comment by herpaderpaldent** [comment]
Whats in your .env file? And are you using docker?

**Comment by trekkie357** [comment]
APP_ENV=local

APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://rircorp.org

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=seat
DB_USERNAME=seat

DB_DEBUG=false

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=redis

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@localhost.local
MAIL_FROM_NAME='SeAT Administrator'

EVE_CLIENT_ID=removed
EVE_CLIENT_SECRET=removed
EVE_CALLBACK_URL=removed

SUPERVISOR_RPC_ADDRESS=127.0.0.1
SUPERVISOR_RPC_USERNAME=seat

SUPERVISOR_RPC_PORT=9001
SUPERVISOR_GROUP=seat

DISCOURSE_URL: http://discourse.rircorp.org
DISCOURSE_API_USERNAME:  trekkie357
DISCOURSE_API_KEY: removed
DISCOURSE_SECRET: removed

**Comment by trekkie357** [comment]
and yes i am using docker

**Comment by herpaderpaldent** [comment]
Ok so i redacted the db pw and app key. Those you should not share 😉

There are possible two reasons. 
1) your discourse is setup to live in a sub ir
2) the one i suspect: the .env did not properly propagate into the docker container. Try restarting it
